### ISSUE TITLE
IDEA: Delete just some of the letters

### ISSUE THREAD

**Issue by achook** [luisvinicius167/ityped#10]
Not issue, but idea.

I think, that an option to delete just some of the letters, not only whole paragraph, would be nice.
For example, "_I like apples"_ is being typed and later only "_apples_" is removed and replaced with "_oranges_".

BTW. Nice library

**Comment by luisvinicius167** [comment]
@KK2345 thanks for the idea! I liked and I hope that ityped can be useful for you ;)

**Comment by luisvinicius167** [comment]
@KK2345 BTW, you can easely reproduce this, using the onFinished function. ;)  
Look: https://jsfiddle.net/u14LnL07/

**Comment by achook** [comment]
Thanks for the idea, @luisvinicius167

---- On Pt, 13 sty 2017 00:17:32 +0100 notifications@github.com wrote ----

@KK2345 BTW, you can easely reproduce this, using the onFinished funciton. ;)
Look: https://jsfiddle.net/u14LnL07/

**Comment by stavros-liaskos** [comment]
it requires 2 different elements though. Would be ideal to add a new property in the config obj so this can work one a single element.
