### ISSUE TITLE
Idea: random delay time between a type action

### ISSUE THREAD

**Issue by crazy4groovy** [luisvinicius167/ityped#11]
`randomDelay: 100` to make the effect look more like a human typing.

Think of the greatness that will ensue! 🏆

**Comment by crazy4groovy** [comment]
https://github.com/luisvinicius167/ityped/blob/master/src/ityped.js#L178

`}, props.startDelay + Math.floor(Math.random() * props.randomDelay))`

**Comment by luisvinicius167** [comment]
@crazy4groovy thanks for your idea! I liked! I will test for see this in action.
