### ISSUE TITLE
init can accept the dom element

### ISSUE THREAD

**Issue by monkindey** [luisvinicius167/ityped#12]
Thanks to awesome ityped !

### Do you want to request a *feature* or report a *bug*?

__feature__

### What is the current behavior?

When I try to combine the vue directive to ityped, I must get the DOM element CSS Path

### What is the expected behavior? 

would wonderful If the init function can accept DOM element type.

**Comment by luisvinicius167** [comment]
@monkindey Hi! So, you need something like: ```init(documentElement, {})```; Where the type of documentElement is an Element or String, as it is now.  If, no, let me know with an example :)

**Comment by luisvinicius167** [comment]
@monkindey Try v0.0.8 now!

**Comment by monkindey** [comment]
Thank you so much. it work in the Vue directive easily now.
https://github.com/monkindey/vue-ityped/blob/master/src/index.js#L15

**Comment by luisvinicius167** [comment]
@monkindey Nice!!
