### ISSUE TITLE
Cancel option

### ISSUE THREAD

**Issue by okvic77** [luisvinicius167/ityped#14]
Is there a cancel method?

I'm using react but if a unmount the view the callback ``onFinished`` still active and generate some errors with ``this.setState`` react method, because the element is not mounted.

Thanks.

**Comment by luisvinicius167** [comment]
@okvic77 Do you have any example?

**Comment by okvic77** [comment]
```
componentDidMount(){
     this.cancel = init(dom, {
        strings: [
          "Hi"
        ],
        onFinished: () => {
          this.setState({ showButton: true });
        }
}
componentWillUnmount() {
    this.cancel(); // The Dom is removed from the body, and the onFinished function is going to fail because is not mounted.
}
```

**Comment by qikkeronline** [comment]
I'd also like a way to do this, as I'm using it on form elements and want to destroy ityped on click, a destroy method would be great 👍

**Comment by luisvinicius167** [comment]
@qikkeronline @okvic77 Try v0.0.9! Let me know if help you! Thanks! ;)
