### ISSUE TITLE
count is not defined (es2015?)

### ISSUE THREAD

**Issue by coderofsalvation** [luisvinicius167/ityped#15]
Interesting, unless I add this line, the browser will throw 'count is not defined':

    +    window.count = 0                                                                                                            
          init('#typer', {       ....}

Maybe this is because im using ityped in an vue2 environment?

**Comment by luisvinicius167** [comment]
@coderofsalvation I don't know... I don't work with Vue. I don't have that problem with React. :(

**Comment by coderofsalvation** [comment]
Ok thanks. Than it *is* a vue-only situation.
Updated the title for SEO purposes + closed comment.
