### ISSUE TITLE
Replicating - typing text twice on same page its not working 

### ISSUE THREAD

**Issue by pgksunilkumar** [luisvinicius167/ityped#17]
I have already setup typing text running fine once on the when i try and run the same command on the same page for second time its doesnot excuete

example fiddle : https://jsfiddle.net/pgksunilkumar/0qq85g51/1/

**Comment by olivierbossel** [comment]
Hi man,

I've updated the code and make a pull request for this feature. You can check here:
https://github.com/luisvinicius167/ityped/pull/19
Hope this will be merged in the repo...
Cheers!

**Comment by luisvinicius167** [comment]
Hi man! Sorry for long time response! Great work :+1:

**Comment by pgksunilkumar** [comment]
It works fine thanks, man Great work 👍 

example : 
https://jsfiddle.net/pgksunilkumar/0qq85g51/4/

**Comment by luisvinicius167** [comment]
Available on v0.0.10! Thanks!!
