### ISSUE TITLE
Can't find a way to reset the strings after initialise it.

### ISSUE THREAD

**Issue by rogeriotaques** [luisvinicius167/ityped#18]
I need to change the strings for a whole new set from time to time. I've tried just to call again the init(), giving the proper parameters, but it didn't work. Then, I tried to call destroy() before reinitialise the component, but no luck!

Any suggestion?

**Comment by luisvinicius167** [comment]
Hi man, sorry for long time response! Try with v0.0.10!

**Comment by rogeriotaques** [comment]
Hi @luisvinicius167, thanks for your reply. Let me try it in another opportunity. I've already fixed my issue using a different approach. Thanks any way. Let me close this issue.
