### ISSUE TITLE
Text doesn't appear in IE11/Win 7

### ISSUE THREAD

**Issue by jeremyhickman** [luisvinicius167/ityped#23]
I've been browser testing a new website in IE11 (Windows 7) and the animation of the text doesn't start, just the blinking cursor.  I've double checked my installation by running your website (https://ityped.surge.sh/) and the same issue can be seen there.

**Comment by marceloavf** [comment]
I think it's a problem with Promise implementation

**Comment by DSchau** [comment]
@jeremyhickman check your console, but I'm thinking that you probably need a Promise polyfill, a la [es6-promise](https://github.com/stefanpenner/es6-promise)

**Comment by jeremyhickman** [comment]
Thanks guys.  Tried that but doesn't seem to help in IE11.  The iTyped website has the same bug in IE11 so perhaps I need to find an alternative typing effect plugin - any suggestions?

**Comment by luisvinicius167** [comment]
Hi, sorry for long response! Please, try v1.0.1. Not using promise now :)
