### ISSUE TITLE
Strings merge after switching tabs

### ISSUE THREAD

**Issue by 110Percent** [luisvinicius167/ityped#29]
While iTyped is printing the string, I can switch to a different tab. However, when I switch back, it seems to be typing a new string without removing the old one. Fortunately, the merged string is removed at the end of the session, but I still don't know how to prevent the merging from occurring.

**Comment by 5uper** [comment]
+1

**Comment by GFWNB** [comment]
+1

**Comment by jayeshanandani** [comment]
+1

**Comment by tryice3** [comment]
+1, in 0.0.5 everything works fine.

**Comment by luisvinicius167** [comment]
Sorry for late reply! Fixed! v1.0.3 👍
