### ISSUE TITLE
Rewriting ityped

### ISSUE THREAD

**Issue by felipe-campos** [luisvinicius167/ityped#5]
As I’ve said in my PR, I really liked your lib and thought I could contribute some tweaks.

As I started digging into it, I was struggling to distribute the ideas into concise and intuitive PRs. So, I decided to just write everything and then reach to you to check if you’re interested in seeing and discussing the changes in order to improve the overall result.

I wouldn’t say I’ve finished, but the code does work and it’s got smaller and easier, imho. It is 107 lines long right now.

What do you say?

Se quiser, podemos falar em português pelo FB. Vou deixar um comentário lá no seu post na JavaScript Brasil.

**Comment by luisvinicius167** [comment]
@felipe-campos Nice! Submit your PR :) Thanks!
