### ISSUE TITLE
forEach is not defined

### ISSUE THREAD

**Issue by baqianxin** [luisvinicius167/ityped#8]
####**请问一下你遇到过这个问题吗**
![image](https://cloud.githubusercontent.com/assets/6780391/21800067/e6287d44-d756-11e6-994e-bd81fd0c0d86.png)

**Comment by luisvinicius167** [comment]
@baqianxin I will check! Which version of browser you're using?

**Comment by baqianxin** [comment]
![image](https://cloud.githubusercontent.com/assets/6780391/21801004/da5c8042-d75a-11e6-86d8-079e904fa455.png)
And thank you for your reply

**Comment by luisvinicius167** [comment]
@baqianxin I'm checking this! When I'm finished, I'll notify you.

**Comment by luisvinicius167** [comment]
@baqianxin try now! Update the ityped version to 0.0.6!

**Comment by baqianxin** [comment]
Thank you very much,
Look at this effect.
![image](https://cloud.githubusercontent.com/assets/6780391/21811148/7fcc383c-d789-11e6-822d-1da96c6fbe9d.png)

http://oom-cc.com/vue-ui/

**Comment by luisvinicius167** [comment]
Wow! Nice! :D @baqianxin
